version: "3.1"

services:

  # # containar postgre sql
  #   db-postgres:
  #     image: postgres:9.6.22-alpine
  #     container_name: postgres
  #     restart: always
  #     ports:
  #       - 5444:5432
  #     environment:
  #       - POSTGRES_DB=postgres_restaurant
  #       - POSTGRES_USER=restaurant
  #       - POSTGRES_PASSWORD=rSUzRBlj4Sbi8625QHilqiCmcuMax2
  #     volumes:
  #       - .:/user/bd/postgres
        
  # # container to redis
  #   db-redis:
  #     image: "redis:alpine3.13"
  #     container_name: redis
  #     restart: always
  #     # command: redis-server --requirepass rSUzRBlj4Sbi8625QHilqiCmcuMax2
  #     ports:
  #       - "6385:6379"
  #     volumes:
  #       - $PWD/redis-data:/var/lib/redis
  #       - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  #     environment:
  #       - REDIS_REPLICATION_MODE=master
  
  # Zookeeper
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2182
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 22182:2182
        
    # Kafka
    kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 29099:29099
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29099
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
