version: "3.1"

services:

  # containar postgre sql
    db-postgres:
      image: postgres:9.6.22-alpine
      container_name: postgres
      restart: always
      ports:
        - 5444:5432
      environment:
        - POSTGRES_DB=postgres_restaurant
        - POSTGRES_USER=restaurant
        - POSTGRES_PASSWORD=rSUzRBlj4Sbi8625QHilqiCmcuMax2
      volumes:
        - .:/user/bd/postgres
        
  # container to redis
    db-redis:
      image: "redis:alpine3.13"
      container_name: redis
      restart: always
      command: redis-server --requirepass rSUzRBlj4Sbi8625QHilqiCmcuMax2
      ports:
        - "6385:6379"
      volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_REPLICATION_MODE=master
  
  # Zookeeper
    zookeeper:
      image: "bitnami/zookeeper:latest"
      container_name: "myapp-zookeeper"
      # networks:
      #   - "myapp"
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        
    # Kafka
    kafka:
      image: bitnami/kafka:2.5.0
      container_name: "myapp-kafka"
      # networks:
      #   - "myapp"
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.35:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

# config to network
# networks:
#   myapp:
#     name: "myapp"
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.0.0/16
#           ip_range: 192.168.0.0/24
#           gateway: 192.168.0.254
#           aux_addresses:
#             kafka: 192.168.0.2
#             zookeeper: 192.168.0.3
